### ISSUE TITLE
Duplicate entry check

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#100]
1. Should email also be checked?
https://github.com/ideafast/ideafast-portal/blob/fe5070c79bb73ae612cbeb090914d7cc49137d79/packages/itmat-interface/src/graphql/resolvers/userResolvers.ts#L248

2. Should uploading existing file be forbidden? Currently it is allowed to upload duplicate files, would it cause confusion or it is not a main issue?

**Comment by sou-chon** [comment]
dup  #109

**Comment by sou-chon** [comment]
Suggest to close this one and make the other one main as this is double issue

**Comment by sou-chon** [comment]
dup #107
