### ISSUE TITLE
Enhance the organisation-related APIs

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#1009]
The following siteIds should be included:

- § K for Kiel
- § G for Muenster (GHI)
- § N for Newcastle
- § E for Rotterdam (Erasmus)
- § H For Harrow
- § Y For Leeds (Yorkshire)
- § D For Devon & Exeter
- § O For Pennine Acute Hospitals (in Manchester - Odham, Rochdale, Fairfield)
- § C For Glasgow (along the river Clyde)
- § M For Manchester
- § Q For QMUL
- § I For Limerick (Ireland) **Conflict with the current one _I for ICL_** 
- § L For Leiden
- § B For Brescia
- § P For Lisbon (Portugal)
- § A For Innsbruck (Austria)
- § W For Warshaw
- § S For Madrid (Spain)
- § R For Stavanger (Rogaland, Norway)
- § T For Testing

**Comment by fguitton** [comment]
We simply cannot reassign a field already in use. There are to many possible problem even if Imperial is the only one, we have a multitude of test files added with time. Most of which are still present in the Object Storage since we have never purged ⚠️

**Comment by wsy19961129** [comment]
While looking into this issue, I found a possible inconsistency:

The frontend use codes from of organizations to validate the sites:
https://github.com/ideafast/ideafast-portal/blob/8457080dc06728bac3a2a12b3eda84710c65964f/packages/itmat-ui-react/src/components/datasetDetail/tabContent/files/fileTab.tsx#L588-L591


While the backend hard-codes the sites for validation:
https://github.com/ideafast/ideafast-portal/blob/8457080dc06728bac3a2a12b3eda84710c65964f/packages/itmat-interface/src/utils/definition.ts#L24-L30

Should we use the organisations in both cases and avoid the hard-coding? @fguitton

**Comment by wsy19961129** [comment]
Regarding the inconsistency, I think one solution maybe like this:
1. Store the organisations totally in the db;
2. All organisations will be used for registration;
3. Organisations with valid siteIdMarket in the metadata field will be used to validate the first letter of a participant Id;
4. Open a new tab in the DMP to let admins manage the organisation in the frontend.

@fguitton What do you think of this?

**Comment by fguitton** [comment]
@wsy19961129 

> 1. Store the organisations totally in the db;

This is already the case, the `organisation` collection contains a `metadata` object with a `siteIDMarker` which should be the tagging letter. It is true however that the front-end is not fetching that information and should.

> 2. All organisations will be used for registration;
I am not quite sure what you mean here.

> 3. Organisations with valid siteIdMarket in the metadata field will be used to validate the first letter of a participant Id;
👍🏼 

> 4. Open a new tab in the DMP to let admins manage the organisation in the frontend.
This is only a feature for us. Lets not forget that this is supposed to be used by other project eventually as well. I think it's a bit larger of a feature than immediately thought about. I can see multiple conflicts. Organizations would have to be managed/attached to a project/dataset/study, the metadata right now are semantically OK in that sense. This means we are missing a lineage. But if we do that we are then opening the option in the future to have multiple times the same organisation registered. We could do this in two stage, with platform admin able to create organization and projects/dataset/study they have access to, and then a project/dataset/study level admin panel allowing to define the metadata. This would be the most elegant but require that we split the existing organisation table. It's a larger conversation.
