### ISSUE TITLE
Download Failed - Server problem

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#103]
Tried to download files from the IDEA_TEST dataset from data.ideafast.eu/ but fail - download started but "Failed -server problem".
![Screen Shot 2020-07-04 at 13 48 58](https://user-images.githubusercontent.com/7723487/86512866-8bea8700-bdfd-11ea-9f7a-ba0cbb7aba39.png)

**Comment by fguitton** [comment]
I have not been able to reproduce this particular issue. I suspect permission issues to be in the way of proper download

**Comment by nguyentb** [comment]
I wasn't able to reproduce the issue as well.
There might be an issue with the internet connection to the server, or the server availability at the time @kai87 downloaded it? Never ever seen this issue in the local deployment.
