### ISSUE TITLE
Download File Name - need to be in the standard format

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#105]
When downloading a file, the filename is still the original file name same as the one before data upload. For all files with names not in standard format, I would suggest we convert the filename to the standard "XXXXXXX-DDDDDDDDD-00000000-00000000.EXT" format to include the metadata.

**Comment by fguitton** [comment]
It is my understanding that this is addressed in f0b9efd2bd2dffcc218ee37e2bf2911bbb127c90:
https://github.com/ideafast/ideafast-portal/blob/f0b9efd2bd2dffcc218ee37e2bf2911bbb127c90/packages/itmat-ui-react/src/components/reusable/fileList/fileList.tsx#L114
