### ISSUE TITLE
Data Upload - do we allow multiple files to be uploaded at the same time?

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#106]
Try to select multiple files for upload on data.ideafast/.eu, but it seems doesn't work - it only allows me to select one file at a time...

**Comment by sou-chon** [comment]
@fguitton i think you can drag and drop multiple files?

**Comment by nguyentb** [comment]
@sou-chon  yes we can drag and drop multiple files :) But if using the file browser it only allows to select 1 file

**Comment by fguitton** [comment]
I'm pretty sure this is addressed by the change below so I'm gonna close this issue

https://github.com/ideafast/ideafast-portal/blob/f5c88f365e243e23ad9baf95802d8697301e22c9/packages/itmat-ui-react/src/components/datasetDetail/tabContent/files/fileTab.tsx#L190
