### ISSUE TITLE
local deployment:  'utf-8-validate' module not found

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#116]
When yarn start,
itmat-interface: Module not found: Error: Can't resolve 'utf-8-validate' in '/home/nguyentb/workspace/IDEA-FAST/ideafast_repo/ideafast-portal/node_modules/ws/lib'

**Comment by fguitton** [comment]
That isn't important as we do not presently rely on web-sockets for IDEAFAST. I would suggest tracking this in the ITMAT repo.
