### ISSUE TITLE
dataset name / rolename should truncate SPACE

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#117]
the "dataset" name and the "role" name allowing space, which can be confusing.
Also when creating role name, it accepts case-sensitive, but showing exactly the same in the list (e.g., it accepts two different roles Role1 and role1, but showing exactly the same ROLE1).
For example: the two dataset named: "abc (1 space) xyz" and "abc (2 spaces) xyz" are allowed, but showing same name in the list as "abc xyz"

![Screenshot from 2020-07-06 12-52-23](https://user-images.githubusercontent.com/1200285/86590700-09420300-bf88-11ea-8163-a9cd18e3e122.png)

**Comment by fguitton** [comment]
That is a good point. I think absolutely every data entry should be trimmed of whitespaces.
I would suggest creating a meta-issue where we can track every single data entry API and and solve all of these issues.
