### ISSUE TITLE
Device ID case-sensitive issue

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#120]
Device ID can be case-sensitive (e.g., MMMAAAAAA and MMMaaaaaa).
However when searching for the device ID, it only considers CAPs letter.
Please see the images for details
![Screenshot from 2020-07-06 12-59-14](https://user-images.githubusercontent.com/1200285/86591123-d6e4d580-bf88-11ea-80bc-b9e7950e8955.png)
![Screenshot from 2020-07-06 12-57-44](https://user-images.githubusercontent.com/1200285/86591124-d77d6c00-bf88-11ea-8e5a-c8903e84e75a.png)

**Comment by fguitton** [comment]
This is expected behaviour. While our package is case sensitive we only enable capitals for IDEAFAST. This is done to avoid confusing users in data entry. However I note that IDs aren't properly capitalised on creation so this will need to be addressed.
