### ISSUE TITLE
Existing file showing incorrect PERIOD

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#121]
When uploading file with the correct format but the order of start-date and end-date is reverse in the filename, it still allows to upload by correctly reverse the order. However, when the file is successfully uploaded, it shows the incorrect order in the existing file lists. Please see the image
![Screenshot from 2020-07-06 13-24-12](https://user-images.githubusercontent.com/1200285/86593310-e108d300-bf8c-11ea-8696-6267fa45191f.png)

**Comment by fguitton** [comment]
It is difficult to understand what the problem is just from a screenshot. Would you be able to provide information regarding the content of your database objects. This will help understand what might be happening here.

**Comment by nguyentb** [comment]
@fguitton : yes, for example the filename is: IAAAAAA-BEDJC6TJT-20200905-20200704.EXT, indicating that the start-date is 2020/09/05, and end-date is 2020/07/04 -> should be wrong. Interestingly, in the upload page, it automatically switches the start-date and end-date, become: start date:  2020/07/04  and end-date 2020/09/05. However, in database, it stores exactly as in the filename (start-date > end-date), which is wrong.

This, You can see in the list of files (figure) that the start-date is 2020/09/05 and end-date is 2020/07/04 :dagger:
