### ISSUE TITLE
Adding IDEA-FAST partners to the registration organisation menu

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#151]
Currently we only have Imperial + 4 clinical sites. Can we have the complete list of IDEA-FAST partners to be selected in the registration?

**Comment by fguitton** [comment]
Do we have that list somewhere ?

**Comment by kai87** [comment]
I think I shared the list to you via Teams a month ago (I think it was a txt, and I changed it to UTF8 ) - let me know if you can't find it :-)

**Comment by fguitton** [comment]
After consideration this mean that we have to :
   - [ ] Add a new backend collection to handle institutions
   - [ ] Provide a way for the institution records to have a site id attached to them.
   - [ ] Allow hierarchical structures to be defined in the collection

**Comment by nguyentb** [comment]
#189 PR has been made for this issue.
