### ISSUE TITLE
Admin doesn't  receive account reactivation requests

### ISSUE THREAD

**Issue by GuanyuTao** [ideafast/ideafast-portal#1724]
These requests don't reach admins. Will check the workflow

**Comment by wsy19961129** [comment]
The requesters can receive the email while the admins can not.
No problems were found while testing on the development environment.

**Comment by wsy19961129** [comment]
This issue only happens on the __master__ brach (nodemailer v6.8.1). If the admin email is admin@example, the admins can not receive the email; while by changing the email to another personal email, the issue disappears.

On the __develop__ branch, there is no such issue.

**Comment by wsy19961129** [comment]
For simplicity, we can only update the version of the nodemailer package.

**Comment by fguitton** [comment]
I guess this is full addressed now.
