### ISSUE TITLE
Apollo Client doesn't refresh all the relevant queries

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#221]
I successfully registered a new account (ks709-test2) and managed to log into the portal. However this new account is not shown in the users page https://data.ideafast.eu/users when I login as the admin.

**Comment by kai87** [comment]
Actually the new account shows up on the users page about 30 mins later..

**Comment by fguitton** [comment]
This is due to the Apollo Client queries not being subscribed to or polled everyso often. We will need to dress a list of such types and proceed from there.
