### ISSUE TITLE
Permission error on deleting files

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#223]
A STANDARD user can still delete a file by making an api request directly even if the delete button on the webpage is invisible to him/her.

**Comment by nguyentb** [comment]
New permission system has been applied to the project, not STANDARD user can still delete a file. Indeed, users with right permission (i.e., ask_required_permissions.manage_study_data) has the right to delete file.
This condition has been already checked.

const hasPermission = await permissionCore.userHasTheNeccessaryPermission(
    task_required_permissions.manage_study_data
...
