### ISSUE TITLE
User organisation info missing from the Users page/Account Information

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#242]
When checking the users on 'Users' page, several users do not have their organisation info shown in the account information: 

![Screen Shot 2020-09-21 at 09 21 49](https://user-images.githubusercontent.com/7723487/93786406-31f0a500-fc27-11ea-9a6d-3af68c3cfd3b.png)

**Comment by nguyentb** [comment]
@kai87  @fguitton  I guess the reason is probably when updating any information of the user, the organisation is set to default (null) so after updating, it becomes null?
