### ISSUE TITLE
Alternative solution for authentication

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#253]

**Comment by nguyentb** [comment]
It's going to be a big task, further discussion is needed

**Comment by nguyentb** [comment]
We plan to implement an authentication mechanism similar to AWS for their rest APIs with access token + digital signature. http://s3.amazonaws.com/doc/s3-developer-guide/RESTAuthentication.html

**Comment by nguyentb** [comment]
This issue is divided into 4 smaller issues:
#298 
#293 
#263 
#262
