### ISSUE TITLE
Replace the value of study ID in log history

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#259]
In the current version when looking into the log history, the study ID is shown as a long string rather than the study/dataset name. Can we replace the string to the dataset name?

![Screen Shot 2020-10-06 at 14 48 56](https://user-images.githubusercontent.com/7723487/95210630-9bee7a00-07e3-11eb-88d0-09ebf864a6c1.png)

**Comment by fguitton** [comment]
We should probably just add it as well as the ID.
It's a perfect first issue for @GuanyuTao

**Comment by GuanyuTao** [comment]
solved this issue in this pr: https://github.com/ideafast/ideafast-portal/pull/292
![1604408612309](https://user-images.githubusercontent.com/9260585/97994045-c9c3e000-1ddc-11eb-9224-85e5327b9a66.jpg)

**Comment by GuanyuTao** [comment]
When user clicks "GET_STUDY", the dataset name will be queried. This brings a new issue: the query operation will be logged again. We may need to improve the log mechanism.
