### ISSUE TITLE
Add section in the admin panel to manage "robot users" based on public keys

### ISSUE THREAD

**Issue by fguitton** [ideafast/ideafast-portal#263]
- [x] New collection for public-key management is created
- [x] New feature to register robot users (a normal user with a public key)
- [x] New feature to link an existing user with a public key
- [x] Create an admin panel to manage robot users (i.e., managing public keys)

**Comment by nguyentb** [comment]
This feature is associated with issue #293

**Comment by nguyentb** [comment]
- [ ] New collection for public management is created
- [ ] New feature to register robot users (a normal user with a public key)
- [ ] New feature to link an existing user with a public key

**Comment by nguyentb** [comment]
Been done in the PR #315
