### ISSUE TITLE
[API] Ensure file digests are available for upload and manifest

### ISSUE THREAD

**Issue by fguitton** [ideafast/ideafast-portal#280]
From conversations with our partners we discussed the use of SHA-256 digest for file upload verification and file listing access.
We need to make sure the API exposes these hashes in a relevant fashion when listing files.

**Comment by wsy19961129** [comment]
More specifically, I guess we need two functions:
1. When a user upload a file, he/she also need to uploads the HASH so that we can verify the completness of the file backend;
2. Provide info of fie HASH when the user get the file list so they can verify the completness themselves?

**Comment by fguitton** [comment]
Absolutely !
