### ISSUE TITLE
Logging improvement

### ISSUE THREAD

**Issue by GuanyuTao** [ideafast/ideafast-portal#305]
In current version, we use ApolloServer plugin `requestDidStart` to record log. The operation name and variables in the request context can be logged. However, the variables in the request context are always ids or username/password which are not readable. This will bring bad user experience to the admin users. One issue on this problem was already created in #259. 

To solve #259 , my solution was to use existing `getStudy` query and resolver to get the dataset name from database via GraphQL. However, the operation will also be logged. This means the admin user will be logged for his `getStudy` behaviour while he is checking the log. A whitelist mechanism cannot tackle this issue as I cannot recognise the admin is visiting the logs or the datasets. 

I propose another two methods to solve this issue:

1.  Create new query and resolvers. The query is only used for logging, and the operation will not be put in the whitelist. But this may also make the project more complex. If giving the best user experience to admin user, we may not only need to show the dataset name, but also the project name,  role name or other information in the database. Thus, a lot of new queries, schema and resolvers should be created. These queries, schema and resolvers will be very similar with existing code, but will have different name. 

2. We use ApolloServer context function instead of plugin. In the context function we have both request and response, so we can get meaningful data(dataset name) in the response and store it in the log collection. In this way, we don't need to create new query and resolvers. However, the log will not be recorded if the request is failed.

I prefer using the first one. But it is big work and we need to design it before coding.

Any ideas? @fguitton @wsy19961129

**Comment by fguitton** [comment]
Following our discussion an approach we could use would be to decorate the output of the logResolver directly, allowing us to customise the data output without haven't to change proxy resolver logic
