### ISSUE TITLE
Log History Details - UI of UPLOAD_FILE Operation 

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#317]
As shown in the screenshot below...

![Screen Shot 2020-11-27 at 15 53 02](https://user-images.githubusercontent.com/7723487/100467812-10021b80-30cb-11eb-94a2-d04e93ba8178.png)

**Comment by GuanyuTao** [comment]
@kai87 I can help with this. How do you want to decorate the details?

**Comment by GuanyuTao** [comment]
Fixed in this pr: #342
