### ISSUE TITLE
Add 4 new devices codes to the DMP

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#322]
WP3 would like to enable uploads of IDF-TEQ (Technology Experience Questionnaire) and Interview Transcripts data to the DMP.

The plan is to use "fixed manually defined device IDs" across all sites that clearly encode the general category of the
data (the participant IDs included in file names will still clearly encode the study site):

InterviewTranscriptsDeviceIDEncodigs:

- IDE-FGX3N3 (German transcripts)
- IEN-DZSSAX (English transcripts)   
- INL-GN65GH (Dutch transcripts)   

IDF-TEQDeviceIDEncoding:

- TEQ-CKQAGP

Can these codes be included as valid device IDs so that data can be uploaded accordingly?

**Comment by GuanyuTao** [comment]
Solved in this PR #324 
![IMG59](https://user-images.githubusercontent.com/9260585/101500562-8c67ea80-3966-11eb-8d99-63af1fc0c981.png)

**Comment by nguyentb** [comment]
Add some more Device IDs
