### ISSUE TITLE
Unable to upload large file (>2GB) due to limited size of "file length"

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#327]
- [ ] This is due to "file_length" is defined as INT which is in the range of (-2,147,483,647, +2,147,483,647).
- [ ] Two possible solutions: (i) change the type of "file length" or (ii) convert the file length to Kilobyte, not Byte.

**Comment by kai87** [comment]
Might be good to keep a file size limit of (e.g.) 8GB?

**Comment by nguyentb** [comment]
> Might be good to keep a file size limit of (e.g.) 8GB?

Yes, it's better to limit the file size (8GB is reasonable atm).
@wsy19961129  We should handle the file size proactively. We could define a global parameter like FILE_SIZE_LIMIT.
