### ISSUE TITLE
Admin 'Users' panel: organisation information disappears after saving new account expiry date

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#415]
After saving new account expiry date for a user, if I click again the 'edit' button for that user, the user's organisation information disappears on the panel. 

![Screen Shot 2021-02-15 at 08 36 14](https://user-images.githubusercontent.com/7723487/107923099-edb0c900-6f68-11eb-97a6-9dc79cd52602.png)

**Comment by nguyentb** [comment]
Solved in PR #424
