### ISSUE TITLE
Can we add an optional "Dataset Description" for each dataset on the DMP?

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#418]
I think it would be great to allow the admin to add a description of the dataset (e.g., on "Administration" panel of that dataset) and display the description on the dataset page. For example, we can have some text like "Device data collected from the Polysomnography (PSG) Study at Kiel" for the PSG study. 

![Screen Shot 2021-02-15 at 17 03 12](https://user-images.githubusercontent.com/7723487/107975628-4d7e9280-6fb0-11eb-8dc8-2322ca40f322.png)

**Comment by wsy19961129** [comment]
![Screenshot from 2021-02-23 13-19-27](https://user-images.githubusercontent.com/21955220/108849214-d1043900-75d9-11eb-9740-6de0477e43f3.png)
![Screenshot from 2021-02-23 13-19-39](https://user-images.githubusercontent.com/21955220/108849227-d3669300-75d9-11eb-8fa6-941fb7481627.png)
