### ISSUE TITLE
The platform automatically logged out during upload

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#437]
This issue is raised by Jay:
- [] The platform automatically logged me out when I was uploading 4 files (total size 10GB) and was logged out during the upload process. One of the four files did successfully upload though. This happened multiple times.

**Comment by wsy19961129** [comment]
Not sure about the exact reason. Tested on the local environment using 4 files (2.44GB each) and no errors found. 

Is it might because the session expires (2h). If the uploading speed is less than 1.45MB/s on average, then the uploading process cannot be finished within 2 hours.
