### ISSUE TITLE
System admins can access the DMP even if their accounts expired...

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#606]
On the 'User' tab it shows @lldcl 's account expired on 20 July, but @lldcl successfully logged onto the DMP on 2 August....

**Comment by fguitton** [comment]
We will be looking into two different solution: 
- [ ] For admin we should remove completely the notion of expiry (on the UI) if it indeed doesn't apply
- [ ] For admin we could make the expiry date enforcement optional
