### ISSUE TITLE
Switch from user admin status to permission check for file deletion

### ISSUE THREAD

**Issue by fguitton** [ideafast/ideafast-portal#98]
The changes introduced in bdd929da6ca94ddeb70ceeef22b9994cce676e62 ought to be reverted once the review of the permission system are done in dsi-icl/itmat-broker#577

https://github.com/ideafast/ideafast-portal/blob/bdd929da6ca94ddeb70ceeef22b9994cce676e62/packages/itmat-ui-react/src/components/reusable/fileList/fileList.tsx#L123-L133

**Comment by fguitton** [comment]
We need to look at multiple level of permissions:
- [ ] User deletes a file they have uploaded themselves
- [ ] User deletes a file from anyone
- [ ] User deletes all files

**Comment by sou-chon** [comment]
Is this still up to date in the released IDEAFAST version?
