### ISSUE TITLE
UploadFile API Extra unnecessary characters

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#987]
1. extra '}' character in the file name;

**Comment by fguitton** [comment]
@wsy19961129 This is very opened. Can you provide more context ? Are those two different issues ?

**Comment by wsy19961129** [comment]
> @wsy19961129 This is very opened. Can you provide more context ? Are those two different issues ?

Sure,

1. When the backend generate the file name from the file description, there is an extra '}' at the end;

2. The logs now could not show the correct information, the reason might be the using of the uploadFile API.

Indeed they are two issues, will open another issue.

**Comment by fguitton** [comment]
> 1. When the backend generate the file name from the file description, there is an extra '}' at the end

Do we have to plan some work to correct this at the DB level ?

**Comment by wsy19961129** [comment]
> > 1. When the backend generate the file name from the file description, there is an extra '}' at the end
> 
> Do we have to plan some work to correct this at the DB level ?

No, this error appears only in the training dataset; and it only affects the name of the file extension.
