### ISSUE TITLE
Lack username in the resetpassword confirmation email.

### ISSUE THREAD

**Issue by wsy19961129** [ideafast/ideafast-portal#99]
Either forgetting username or email will be asked to reset the password, but the confirmation email does not contain information about the username, which compulsory when logging in. 

Thus if someone forget his/her username and reset the passwork via the link, he/she still could not get his/her username and cannot login.

**Comment by sou-chon** [comment]
Right, i think i didn't wire it up all the way for that. now in the UI it's only "forget email". but "forget username" is available via API. should change the wording on the UI

**Comment by sou-chon** [comment]
I just check....seems like it does send the username?
```
Dear Chan Tai Man,



Your username is standardUser.


You can reset you password by click the following link (active for 1 hour):

http://localhost:3000/resetPassword/standardUser/792a9611-446b-4c5c-b28f-c76f0dd81c42



Yours truly, NAME team.
```
